[package]
name = "pea-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "pea-server"
path = "src/server.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
