name: Client Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: create config.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "config.json"
          json: '{"SERVER_URL":"http://localhost:8080"}'
          dir: "client/"
      - name: Run Tests
        run: |
          npm install
          npm test
      - name: Run linter
        run: |
          npx eslint .
